from defs import MIN_VALUE_50K_SAT

DEBUG_PRICE_RATE = 1.5
ROUND_PRECISION = 4
MIN_TRADE_ALLOWED = MIN_VALUE_50K_SAT
MIN_COMPETITOR_ORDER_VOLUME = 0.007
MACD_ADVICE_UPDATE_TIME = 1 * 60
MACD_HIST_ZERO_DRIFT_THRESHOLD = 1.0

ORDERS_TYPE = 'limit'